"""Executable analytical models for HgCdTe research."""

from .gauge import (
    AlignmentDiagnostics,
    GaugeAlignmentError,
    KANE_IRREP_BLOCKS,
    align_basis,
    parallel_transport_sequence,
    procrustes_unitary,
    rotate_operator,
)
from .kane8 import (
    ALPHA_EV_A2,
    ExtendedKaneParameters,
    KaneParameters,
    hamiltonian,
    hamiltonian_two_p,
    time_reversal_residual,
    time_reversal_residual_two_p,
)
from .projection import (
    OBSERVATION_DIMENSION,
    closure_residual,
    covariance_whitener,
    design_diagnostics,
    extended_closure_residual,
    extended_design_diagnostics,
    fit_extended_parameters,
    fit_parameters,
    parameter_templates,
)
from .symmetry import (
    forbidden_gamma_coupling_norm,
    gamma_irrep_residual,
    gamma_irrep_symmetrize,
    hermitize,
    time_reversal_pair_residual,
    time_reversal_pair_symmetrize,
)

__all__ = [
    "ALPHA_EV_A2",
    "AlignmentDiagnostics",
    "ExtendedKaneParameters",
    "GaugeAlignmentError",
    "KANE_IRREP_BLOCKS",
    "KaneParameters",
    "OBSERVATION_DIMENSION",
    "align_basis",
    "closure_residual",
    "covariance_whitener",
    "design_diagnostics",
    "extended_closure_residual",
    "extended_design_diagnostics",
    "fit_extended_parameters",
    "fit_parameters",
    "forbidden_gamma_coupling_norm",
    "gamma_irrep_residual",
    "gamma_irrep_symmetrize",
    "hamiltonian",
    "hamiltonian_two_p",
    "hermitize",
    "parallel_transport_sequence",
    "parameter_templates",
    "procrustes_unitary",
    "rotate_operator",
    "time_reversal_pair_residual",
    "time_reversal_pair_symmetrize",
    "time_reversal_residual",
    "time_reversal_residual_two_p",
]
