"""Executable analytical models for HgCdTe research."""

from .code_exports import (
    ExportDefaults,
    ExportFormatError,
    NetcdfFieldMap,
    dataset_from_arrays,
    load_jsonl_matrix_export,
    load_netcdf_matrix_export,
)
from .dataio import (
    MatrixDataset,
    MatrixRecord,
    file_sha256,
    load_matrix_dataset,
    save_matrix_dataset,
)
from .gauge import (
    AlignmentDiagnostics,
    GaugeAlignmentError,
    KANE_IRREP_BLOCKS,
    align_basis,
    parallel_transport_sequence,
    procrustes_unitary,
    rotate_operator,
)
from .kane8 import (
    ALPHA_EV_A2,
    ExtendedKaneParameters,
    KaneParameters,
    hamiltonian,
    hamiltonian_two_p,
    time_reversal_residual,
    time_reversal_residual_two_p,
)
from .pipeline import (
    ProcessingDiagnostics,
    process_record,
    project_covariance,
    real_linear_map,
    rotate_covariance,
    rotation_from_overlap,
)
from .projection import (
    OBSERVATION_DIMENSION,
    closure_residual,
    covariance_whitener,
    design_diagnostics,
    extended_closure_residual,
    extended_design_diagnostics,
    fit_extended_parameters,
    fit_parameters,
    parameter_templates,
)
from .symmetry import (
    forbidden_gamma_coupling_norm,
    gamma_irrep_residual,
    gamma_irrep_symmetrize,
    hermitize,
    time_reversal_pair_residual,
    time_reversal_pair_symmetrize,
)

__all__ = [
    "ALPHA_EV_A2",
    "AlignmentDiagnostics",
    "ExportDefaults",
    "ExportFormatError",
    "ExtendedKaneParameters",
    "GaugeAlignmentError",
    "KANE_IRREP_BLOCKS",
    "KaneParameters",
    "MatrixDataset",
    "MatrixRecord",
    "NetcdfFieldMap",
    "OBSERVATION_DIMENSION",
    "ProcessingDiagnostics",
    "align_basis",
    "closure_residual",
    "covariance_whitener",
    "dataset_from_arrays",
    "design_diagnostics",
    "extended_closure_residual",
    "extended_design_diagnostics",
    "file_sha256",
    "fit_extended_parameters",
    "fit_parameters",
    "forbidden_gamma_coupling_norm",
    "gamma_irrep_residual",
    "gamma_irrep_symmetrize",
    "hamiltonian",
    "hamiltonian_two_p",
    "hermitize",
    "load_jsonl_matrix_export",
    "load_matrix_dataset",
    "load_netcdf_matrix_export",
    "parallel_transport_sequence",
    "parameter_templates",
    "process_record",
    "project_covariance",
    "procrustes_unitary",
    "real_linear_map",
    "rotate_covariance",
    "rotate_operator",
    "rotation_from_overlap",
    "save_matrix_dataset",
    "time_reversal_pair_residual",
    "time_reversal_pair_symmetrize",
    "time_reversal_residual",
    "time_reversal_residual_two_p",
]
