#!/usr/bin/env python3
r"""Portable LaTeX compatibility entry point for the SST bundle builder.

The scientific/source builder remains in ``build_sst_submission_bundle``. This
module fixes document-engine and source compatibility at the public submission
entry point:

- remove legacy ``mathptmx`` so standard symbols such as ``\hbar`` remain
  defined under the minimal TeX installation;
- disable microtype font expansion, which requires optional scalable T1 fonts,
  while retaining character protrusion;
- permit inclusion of the vector PDF 1.7 figures generated by librsvg;
- preserve accented author names while converting unsupported Unicode relation
  symbols in prose to portable text equivalents;
- normalize two known inline-delimiter defects in the controlled Markdown;
- render inverse angstroms with a math-safe ring accent;
- keep source-only archives byte deterministic by packaging the immutable SVG
  figures directly instead of invoking a PDF converter that writes metadata.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil

from tools import build_sst_submission_bundle as core

_ORIGINAL_PREAMBLE = core._preamble
_ORIGINAL_MARKDOWN_TO_LATEX = core._markdown_to_latex
_ORIGINAL_CONVERT_FIGURES = core._convert_figures


def _portable_preamble(*, title: str, author_block: str, pdf_author: str) -> str:
    preamble = _ORIGINAL_PREAMBLE(
        title=title,
        author_block=author_block,
        pdf_author=pdf_author,
    )
    preamble = preamble.replace(r"\usepackage{mathptmx}", "")
    preamble = preamble.replace(
        r"\usepackage{microtype}",
        r"\usepackage[protrusion=true,expansion=false]{microtype}",
    )
    return "\\pdfminorversion=7\n" + preamble


def _portable_unicode(text: str) -> str:
    replacements = {
        "–": "--",
        "—": "---",
        "−": "-",
        "“": "``",
        "”": "''",
        "‘": "`",
        "’": "'",
        "µ": "micro",
        "μ": "micro",
        "≤": "<=",
        "≥": ">=",
        "×": "x",
        "±": "+/-",
        "√": "sqrt",
        " ": " ",
    }
    for source, target in replacements.items():
        text = text.replace(source, target)
    return text


def _portable_markdown_to_latex(markdown: str) -> str:
    corrections = {
        r"At $\sigma_x=0.005`": r"At $\sigma_x=0.005$",
        r"At $\sigma_x=0.010`": r"At $\sigma_x=0.010$",
        r"$\mathrm{\AA^{-1}}$": r"$\mathrm{\mathring{A}^{-1}}$",
    }
    for source, target in corrections.items():
        markdown = markdown.replace(source, target)

    malformed = (
        r"$\sigma_x=0.005`",
        r"$\sigma_x=0.010`",
        r"\mathrm{\AA^{-1}}",
    )
    remaining = [token for token in malformed if token in markdown]
    if remaining:
        raise ValueError(f"unresolved portable-Markdown defects: {remaining}")
    return _ORIGINAL_MARKDOWN_TO_LATEX(markdown)


def _portable_convert_figures(
    asset_dir: Path,
    figure_dir: Path,
    *,
    require_tools: bool,
) -> list[Path]:
    if require_tools:
        return _ORIGINAL_CONVERT_FIGURES(
            asset_dir,
            figure_dir,
            require_tools=True,
        )

    figure_dir.mkdir(parents=True, exist_ok=True)
    copied: list[Path] = []
    for svg_name in core.FIGURE_FILES:
        source = asset_dir / svg_name
        target = figure_dir / svg_name
        shutil.copyfile(source, target)
        copied.append(target)
    return copied


core._preamble = _portable_preamble
core._normalize_unicode = _portable_unicode
core._markdown_to_latex = _portable_markdown_to_latex
core._convert_figures = _portable_convert_figures
build = core.build


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repository-root", default=".")
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--compile", action="store_true", dest="compile_pdf")
    parser.add_argument("--commit-sha", default="unknown")
    args = parser.parse_args()
    result = build(
        args.repository_root,
        args.output_dir,
        compile_pdf=args.compile_pdf,
        commit_sha=args.commit_sha,
    )
    print(json.dumps(result, sort_keys=True))


if __name__ == "__main__":
    main()
