#!/usr/bin/env python3
r"""Portable LaTeX compatibility entry point for the SST bundle builder.

The scientific/source builder remains in ``build_sst_submission_bundle``. This
module fixes document-engine compatibility at the public submission entry point:

- remove legacy ``mathptmx`` so standard symbols such as ``\hbar`` remain
  defined under the minimal TeX installation;
- permit inclusion of the vector PDF 1.7 figures generated by librsvg;
- preserve accented author names while converting unsupported Unicode relation
  symbols in prose to portable text equivalents.
"""
from __future__ import annotations

import argparse
import json

from tools import build_sst_submission_bundle as core

_ORIGINAL_PREAMBLE = core._preamble


def _portable_preamble(*, title: str, author_block: str, pdf_author: str) -> str:
    preamble = _ORIGINAL_PREAMBLE(
        title=title,
        author_block=author_block,
        pdf_author=pdf_author,
    )
    preamble = preamble.replace(r"\usepackage{mathptmx}\n", "")
    return "\\pdfminorversion=7\n" + preamble


def _portable_unicode(text: str) -> str:
    replacements = {
        "–": "--",
        "—": "---",
        "−": "-",
        "“": "``",
        "”": "''",
        "‘": "`",
        "’": "'",
        "µ": "micro",
        "μ": "micro",
        "≤": "<=",
        "≥": ">=",
        "×": "x",
        "±": "+/-",
        "√": "sqrt",
        " ": " ",
    }
    for source, target in replacements.items():
        text = text.replace(source, target)
    return text


core._preamble = _portable_preamble
core._normalize_unicode = _portable_unicode
build = core.build


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repository-root", default=".")
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--compile", action="store_true", dest="compile_pdf")
    parser.add_argument("--commit-sha", default="unknown")
    args = parser.parse_args()
    result = build(
        args.repository_root,
        args.output_dir,
        compile_pdf=args.compile_pdf,
        commit_sha=args.commit_sha,
    )
    print(json.dumps(result, sort_keys=True))


if __name__ == "__main__":
    main()
