#!/usr/bin/env python3
"""Validate the complete CdTe Gamma-point Td double-group Kane basis.

All target matrices are generated by multiplying the already matched C3[111]
and S4z lifts. No independent principal SU(2) lift is chosen for any other
operation. This preserves one global double-group multiplication table and
resolves the operation-dependent central-sign ambiguity.
"""
from __future__ import annotations

import argparse
from collections import deque
import hashlib
import json
import math
from pathlib import Path
import sys
from typing import Any

import numpy as np

TOOLS = Path(__file__).resolve().parent
if str(TOOLS) not in sys.path:
    sys.path.insert(0, str(TOOLS))
from analyze_kane_symmetry_intertwiner import (  # noqa: E402
    fix_time_reversal_phase,
    intertwiner,
    rotation,
    target_blocks,
    time_reversal_blocks,
)

LABELS = ("Gamma6", "Gamma8", "Gamma7")
DIMS = {"Gamma6": 2, "Gamma8": 4, "Gamma7": 2}


def _sha256(path: str | Path) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for chunk in iter(lambda: stream.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _complex(payload: Any) -> np.ndarray:
    array = np.asarray(payload, dtype=float)
    if array.ndim != 3 or array.shape[-1] != 2:
        raise ValueError(f"invalid serialized complex matrix shape {array.shape}")
    return array[..., 0] + 1j * array[..., 1]


def _serialized(matrix: np.ndarray) -> list[list[list[float]]]:
    return [
        [[float(value.real), float(value.imag)] for value in row]
        for row in np.asarray(matrix, dtype=complex)
    ]


def _generator_data() -> dict[str, tuple[np.ndarray, dict[str, np.ndarray]]]:
    c3 = rotation((1.0, 1.0, 1.0), 2.0 * math.pi / 3.0)
    s4 = np.array([[0.0, -1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, -1.0]])
    return {
        "C": (c3, dict(zip(LABELS, target_blocks(c3), strict=True))),
        "S": (s4, dict(zip(LABELS, target_blocks(s4), strict=True))),
    }


def generate_td_double_group(tolerance: float = 1e-10) -> list[dict[str, Any]]:
    """Generate the 48 lifted operations and verify the 24 central pairs."""
    identity = {
        "word": "",
        "rotation": np.eye(3),
        "blocks": {label: np.eye(DIMS[label], dtype=complex) for label in LABELS},
    }
    elements = [identity]
    queue: deque[int] = deque([0])
    generators = _generator_data()
    while queue:
        current = elements[queue.popleft()]
        for symbol, (spatial, blocks) in generators.items():
            candidate = {
                "word": current["word"] + symbol,
                "rotation": current["rotation"] @ spatial,
                "blocks": {
                    label: current["blocks"][label] @ blocks[label]
                    for label in LABELS
                },
            }
            duplicate = any(
                np.linalg.norm(candidate["rotation"] - known["rotation"]) <= tolerance
                and np.linalg.norm(
                    candidate["blocks"]["Gamma6"] - known["blocks"]["Gamma6"]
                )
                <= tolerance
                for known in elements
            )
            if not duplicate:
                elements.append(candidate)
                queue.append(len(elements) - 1)
                if len(elements) > 48:
                    raise RuntimeError("C3/S4 generated more than 48 double-group lifts")
    if len(elements) != 48:
        raise RuntimeError(f"expected 48 double-group lifts, got {len(elements)}")

    spatial_groups: list[list[dict[str, Any]]] = []
    for element in elements:
        for group in spatial_groups:
            if np.linalg.norm(element["rotation"] - group[0]["rotation"]) <= tolerance:
                group.append(element)
                break
        else:
            spatial_groups.append([element])
    if len(spatial_groups) != 24 or any(len(group) != 2 for group in spatial_groups):
        raise RuntimeError("expected two double-group lifts for each of 24 Td operations")
    if any(
        np.linalg.norm(group[0]["blocks"]["Gamma6"] + group[1]["blocks"]["Gamma6"])
        > 1e-9
        for group in spatial_groups
    ):
        raise RuntimeError("a central pair does not differ by the spinor minus sign")
    return elements


def _match(
    operation: dict[str, Any],
    elements: list[dict[str, Any]],
    rotation_tolerance: float,
    spinor_tolerance: float,
) -> tuple[int, dict[str, Any], float, float]:
    spatial = np.asarray(operation["rotation_cartesian"], dtype=float)
    spinor = _complex(operation["spinor_rotation"])
    matches = []
    for index, element in enumerate(elements):
        r_residual = float(np.linalg.norm(spatial - element["rotation"]))
        s_residual = float(np.linalg.norm(spinor - element["blocks"]["Gamma6"]))
        if r_residual <= rotation_tolerance and s_residual <= spinor_tolerance:
            matches.append((index, element, r_residual, s_residual))
    if len(matches) != 1:
        nearest = min(
            (
                float(np.linalg.norm(spatial - element["rotation"])),
                float(np.linalg.norm(spinor - element["blocks"]["Gamma6"])),
                element["word"],
            )
            for element in elements
        )
        raise RuntimeError(
            f"operation {operation['index']} matched {len(matches)} lifts; nearest={nearest}"
        )
    return matches[0]


def validate(probe: dict[str, Any], contract: dict[str, Any]) -> dict[str, Any]:
    thresholds = contract["thresholds"]
    r_tol = float(thresholds["operation_rotation_frobenius"])
    s_tol = float(thresholds["operation_spinor_frobenius"])
    m_tol = float(thresholds["all_operation_matrix_frobenius"])
    null_tol = float(thresholds["intertwiner_null_singular_value"])
    next_min = float(thresholds["next_singular_value_minimum"])
    if int(probe["unitary_operation_count"]) != 24:
        raise RuntimeError("probe does not contain exactly 24 unitary operations")
    if int(probe["antiunitary_operation_count"]) != 24:
        raise RuntimeError("probe does not contain exactly 24 antiunitary operations")
    if any(item.get("matrix_status") != "available" for item in probe["operations"]):
        raise RuntimeError("probe contains a missing matrix block")

    operations = {int(item["index"]): item for item in probe["operations"]}
    if len(operations) != 48:
        raise RuntimeError("probe operation indices are not unique")
    generator_indices = {
        item["name"]: int(item["operation_index"]) for item in contract["generators"]
    }
    c3_index = generator_indices["C3_[111]"]
    s4_index = generator_indices["S4_z"]
    tr_index = int(contract["pure_time_reversal_operation_index"])
    if operations[c3_index]["time_reversal"] or operations[s4_index]["time_reversal"]:
        raise RuntimeError("a declared spatial generator is antiunitary")
    if not operations[tr_index]["time_reversal"]:
        raise RuntimeError("the declared time-reversal operation is unitary")

    targets = _generator_data()
    tr_targets = dict(zip(LABELS, time_reversal_blocks(), strict=True))
    specs = {item["irrep"]: item for item in contract["energy_blocks"]}
    intertwiners: dict[str, np.ndarray] = {}
    irrep_results: dict[str, dict[str, Any]] = {}
    for label in ("Gamma7", "Gamma8", "Gamma6"):
        block = int(specs[label]["probe_block_index"])
        calculated = [
            _complex(operations[index]["unitary_blocks"][block])
            for index in (c3_index, s4_index)
        ]
        expected = [targets[symbol][1][label] for symbol in ("C", "S")]
        unitary, singular_values, generator_residual = intertwiner(
            calculated, expected
        )
        unitary, tr_residual = fix_time_reversal_phase(
            unitary,
            _complex(operations[tr_index]["unitary_blocks"][block]),
            tr_targets[label],
        )
        nullity = int(np.sum(singular_values <= null_tol))
        next_value = float(singular_values[-2])
        if nullity != 1 or next_value < next_min:
            raise RuntimeError(
                f"{label} intertwiner is not unique: nullity={nullity}, next={next_value}"
            )
        if max(generator_residual, tr_residual) > m_tol:
            raise RuntimeError(f"{label} generator/time-reversal residual exceeds gate")
        intertwiners[label] = unitary
        irrep_results[label] = {
            "bands_one_based": specs[label]["bands_one_based"],
            "probe_block_index": block,
            "intertwiner": _serialized(unitary),
            "intertwiner_unitarity_residual": float(
                np.linalg.norm(unitary.conj().T @ unitary - np.eye(unitary.shape[0]))
            ),
            "generator_intertwiner_nullity": nullity,
            "generator_smallest_singular_value": float(singular_values[-1]),
            "generator_next_singular_value": next_value,
            "generator_symmetry_residual": float(generator_residual),
            "pure_time_reversal_residual": float(tr_residual),
            "maximum_unitary_residual": 0.0,
            "maximum_antiunitary_residual": 0.0,
        }

    elements = generate_td_double_group()
    unitary_section: set[int] = set()
    antiunitary_section: set[int] = set()
    records = []
    max_rotation = 0.0
    max_spinor = 0.0
    for operation in sorted(probe["operations"], key=lambda item: int(item["index"])):
        element_index, element, r_residual, s_residual = _match(
            operation, elements, r_tol, s_tol
        )
        antiunitary = bool(operation["time_reversal"])
        (antiunitary_section if antiunitary else unitary_section).add(element_index)
        max_rotation = max(max_rotation, r_residual)
        max_spinor = max(max_spinor, s_residual)
        residuals = {}
        for label in ("Gamma7", "Gamma8", "Gamma6"):
            block = int(specs[label]["probe_block_index"])
            calculated = _complex(operation["unitary_blocks"][block])
            unitary = intertwiners[label]
            if antiunitary:
                canonical = unitary.conj().T @ calculated @ unitary.conj()
                expected = element["blocks"][label] @ tr_targets[label]
                field = "maximum_antiunitary_residual"
            else:
                canonical = unitary.conj().T @ calculated @ unitary
                expected = element["blocks"][label]
                field = "maximum_unitary_residual"
            residual = float(np.linalg.norm(canonical - expected))
            if residual > m_tol:
                raise RuntimeError(
                    f"operation {operation['index']} {label} residual {residual} exceeds gate"
                )
            residuals[label] = residual
            irrep_results[label][field] = max(irrep_results[label][field], residual)
        records.append(
            {
                "operation_index": int(operation["index"]),
                "time_reversal": antiunitary,
                "double_group_word": element["word"] or "identity",
                "double_group_element_index": element_index,
                "rotation_mapping_residual": r_residual,
                "spinor_lift_mapping_residual": s_residual,
                "canonical_matrix_residuals": residuals,
            }
        )
    if len(unitary_section) != 24 or len(antiunitary_section) != 24:
        raise RuntimeError("unitary or antiunitary section does not span 24 lifts")
    if unitary_section != antiunitary_section:
        raise RuntimeError("unitary and antiunitary operations use different lift sections")

    maximum = max(
        max(item["maximum_unitary_residual"], item["maximum_antiunitary_residual"])
        for item in irrep_results.values()
    )
    return {
        "schema_version": "1.0",
        "status": "validated_full_cdte_gamma_double_group_canonical_basis",
        "upstream": contract.get("upstream", {}),
        "probe_data_file_schema_sha256": probe["data_file_schema_sha256"],
        "space_group_name": probe["space_group_name"],
        "space_group_number": probe["space_group_number"],
        "selected_global_bands_one_based": probe["selected_global_bands_one_based"],
        "generator_operation_indices": {
            "C3_[111]": c3_index,
            "S4_z": s4_index,
            "pure_time_reversal": tr_index,
        },
        "double_group_element_count": len(elements),
        "unitary_operation_count": len(unitary_section),
        "antiunitary_operation_count": len(antiunitary_section),
        "maximum_operation_rotation_mapping_residual": max_rotation,
        "maximum_operation_spinor_lift_mapping_residual": max_spinor,
        "maximum_canonical_matrix_residual": maximum,
        "irreps": irrep_results,
        "operations": records,
        "remaining_freedom": (
            "One relative discrete sign per inequivalent irrep remains. Fix those signs "
            "only with a declared linear-k Kane matrix-element convention."
        ),
        "claim_boundary": contract["claim_boundary"],
        "authorization": contract["authorization"],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("probe_json")
    parser.add_argument("--contract", required=True)
    parser.add_argument("--output-json", required=True)
    args = parser.parse_args()
    probe = json.loads(Path(args.probe_json).read_text(encoding="utf-8"))
    contract = json.loads(Path(args.contract).read_text(encoding="utf-8"))
    if contract.get("stage") != "cdte_kane_double_group_gate":
        raise ValueError("unexpected double-group contract stage")
    result = validate(probe, contract)
    result["probe_json_sha256"] = _sha256(args.probe_json)
    rendered = json.dumps(result, indent=2, sort_keys=True) + "\n"
    Path(args.output_json).write_text(rendered, encoding="utf-8")
    print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
